name: ApexFood CI - Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      # Serviço de SQL Server para os testes
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "Str0ng_Passw0rd_123!"
        ports:
          - 1433:1433
        options: >-
          --health-cmd "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Str0ng_Passw0rd_123! -Q 'SELECT 1'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 20

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Run unit tests
        run: dotnet test ApexFood.UnitTests/ApexFood.UnitTests.csproj --configuration Release --no-build --verbosity normal

      - name: Run integration tests
        run: dotnet test ApexFood.Api.IntegrationTests/ApexFood.Api.IntegrationTests.csproj --configuration Release --no-build --verbosity normal
